version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/flask-docker/app
    networks:
      - flask-api
    depends_on:
      - postgres
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: flask-api
      POSTGRES_USER: developermallon
      POSTGRES_PASSWORD: zbM@!!0n
    networks:
      - flask-api
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ti@mallon.com.br
      PGADMIN_DEFAULT_PASSWORD: zbM@!!0n
    ports:
      - "5050:80"
    networks:
      - flask-api
    depends_on:
      - postgres

networks:
  flask-api:
    driver: bridge

volumes:
  postgres_data:

