version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/flask-docker/app
    networks:
      - flask-api
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask-api.rule=Host(`flask-api.mallon.clik`)"
      # - "traefik.http.services.flask-api.loadbalancer.server.port=5000"
      - "traefik.http.routers.flask-api.entrypoints=websecure"
      - "traefik.http.routers.flask-api.tls.certresolver=leresolver"
      - "traefik.http.routers.flask-api.service=flask-api"

networks:
  flask-api:
    driver: bridge



